baseURL = "https://bistrotheme.netlify.com/"
title = "My New Hugo Site"

[params]
  imagewithtitle = "HOT Deal of the Day"
  imagewithdesc = "Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore nulla facilisis. velit esse molestie consequat, vel illum dolore nulla facilisis."
  imagewithbtn = "<a href='#order-form' class='btn-common-white page-scroll'>Order Now</a>"
  happycustomer = "4680"
  dishesserved = "865"
  totalbevegage = "510"
  cupofcoffe = "1350"
  formdesc = "Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat."
  copyright = "Copyright &copy; 2016 Bistro. All Right Reserved"
  facebook = "https://www.facebook.com"
  twitter = "https://www.twitter.com"
  google = "https://plus.google.com"
  whysitetitle = "Why Bistro?"
  whysitesmalldesc = "Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore dolor in hendrerit in vulputate."
  whysiteanotherdesc = "Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl."
  getintouch = "Restaurant, to consequat ipsum nec sagittis sem."
  newslettertitle = "Sign up with your name and email to get updates fresh updates."
  address = "Restaurant, Manhattan 1258,New York, USA Lahore"
  mobile = "(+1) 234 567 8901"
  email = "hello@website.com"

[menu]
  # Shown in the header menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Our Food"
    weight = 2
    identifier = "ourfood"
    url = "/food/"
  [[menu.main]]
    name = "Pages"
    weight = 3
    identifier = "pages"
    url = "#"
      [[menu.main]]
        name = "About Us"
        weight = 4
        parent = "pages"
        url = "/about/"
      [[menu.main]]
        name = "Menu"
        weight = 5
        parent = "pages"
        url = "/menu/"
      [[menu.main]]
        name = "Blog Detail"
        weight = 6
        parent = "pages"
        url = "/blog/"
      [[menu.main]]
        name = "FAQ"
        weight = 7
        parent = "pages"
        url = "/faq/"
   [[menu.main]]
      name = "Gallery"
      weight = 8
      identifier = "gallery"
      url = "#"
        [[menu.main]]
          name = "Gallery Two Column"
          weight = 9
          parent = "gallery"
          url = "#"
        [[menu.main]]
          name = "Gallery Three Column"
          weight = 10
          parent = "gallery"
          url = "#"
        [[menu.main]]
          name = "Gallery Four Column"
          weight = 11
          parent = "gallery"
          url = "#"
    [[menu.main]]
      name = "Blog"
      weight = 12
      identifier = "blog"
      url = "#"
    [[menu.main]]
      name = "Order Now"
      weight = 13
      identifier = "ordernow"
      url = "#"
    [[menu.main]]
      name = "Location"
      weight = 14
      identifier = "loaction"
      url = "#"
        [[menu.main]]
          name = "Location V1"
          weight = 15
          parent = "loaction"
          url = "#"
        [[menu.main]]
          name = "Location V2"
          weight = 16
          parent = "loaction"
          url = "#"
